### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by jkutner** [jkutner/mjruby#2]
Add FreeBSD to the cross compile and test it.

**Comment by rtyler** [comment]
@jkutner is Docker required to compile or is that just a nice-to-have to make the development easy? I've got a number of FreeBSD (10-STABLE and 11-CURRENT) machines floating around that I could test on

**Comment by jkutner** [comment]
Yes, docker is required. And I want to be able to cross compile even without the native machine. I think this may be something that needs to be fixed in mruby.

**Comment by hone** [comment]
We should be able to add freebsd cross compilation support either to [mruby-cli](https://github.com/hone/mruby-cli) or just to this project in `build_config.rb`. I have limited experience with freebsd. @rtyler do you know the host triplet I'd use? According to [this doc](http://marcelog.github.io/articles/cross_freebsd_compiler_in_linux.html) we should be able to use something like `x86_64-pc-freebsd7`, but I'm not sure if 7 is the right version. Also, we'll have to see how hard it is to compile the mruby deps.
