### ISSUE TITLE
How do you make this work w/ rvm?

### ISSUE THREAD

**Issue by rebelwarrior** [jkutner/mjruby#5]
Hi I downloaded the executable and placed it in the location `~/.rvm/rubies/jruby-9.0.0.0/bin` and set JRUBY_HOME  to `~/.rvm/rubies/jruby-9.0.0.0/` (JAVA_HOME is already set correctly) and couldn't get it to work. Got this error:
`RuntimeError: JRUBY_HOME directory is malformed: no lib directory found!`
Any ideas? 

And this is a super cool idea, btw.

**Comment by jkutner** [comment]
@rebelwarrior i can't reproduce :( what platform are you on?

**Comment by jkutner** [comment]
make sure you also `rvm use jruby-9.0.0.0` after doing that

**Comment by rebelwarrior** [comment]
I am on Mac OS X 9.5, I just installed the 64 bit one but still get the directory is malformed issue. Investigating further.

**Comment by rebelwarrior** [comment]
``` bash
$ which jruby
/Users/davidacevedo/.rvm/rubies/jruby-9.0.0.0/bin/jruby
$ JRUBY_HOME='~/.rvm/rubies/jruby-9.0.0.0/'
$ echo $JRUBY_HOME
~/.rvm/rubies/jruby-9.0.0.0/
$ mjruby pry
RuntimeError: JRUBY_HOME directory is malformed: no lib directory found!
```

**Comment by jkutner** [comment]
Can you give this another try with v0.2. I don't know what might have fixed it, but I changed a lot.

**Comment by rebelwarrior** [comment]
using `export JRUBY_HOME="/Users/username/.rvm/rubies/jruby-9.0.0.0"` using the full path seemed to do the trick.

**Comment by jkutner** [comment]
I'm gonna keep this open, because that shouldn't matter.

**Comment by jkutner** [comment]
Are any of those directories symlinks? (i thought i have that covered)

**Comment by jkutner** [comment]
This should be fixed now that the Gem packaging is available.
